name: mapsindoors_mapbox
description: A MapsIndoors flutter plugin using the Mapbox platform for Android and iOS app usage.
version: 2.1.0
repository: https://github.com/MapsPeople/mapsindoors_flutter_mapbox
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mapsindoors_mapbox_android
      ios:
        default_package: mapsindoors_mapbox_ios

dependencies:
  flutter:
    sdk: flutter
  mapsindoors_mapbox_android: ^2.1.0
  mapsindoors_mapbox_ios: ^2.1.0
  mapsindoors_platform_interface: ^2.1.0
dependency_overrides:
  mapsindoors_mapbox_android:
    path: ../mapsindoors_mapbox_android
  mapsindoors_mapbox_ios:
    path: ../mapsindoors_mapbox_ios
  mapsindoors_platform_interface:
    path: ../../misdkfl-platform


dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0