name: mapsindoors_mapbox
description: A MapsIndoors flutter plugin using the Mapbox platform for Android and iOS app usage.
version: 4.2.2
repository: https://github.com/MapsPeople/mapsindoors_flutter_mapbox
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mapsindoors_mapbox_android
      ios:
        default_package: mapsindoors_mapbox_ios

dependencies:
  flutter:
    sdk: flutter
  mapsindoors_mapbox_android: ^4.2.2
  mapsindoors_mapbox_ios: ^4.2.2
  mapsindoors_platform_interface: ^4.2.2


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0