name: mapsindoors_platform_interface
description: A common platform interface for the mapsindoors plugin.
version: 2.0.0
repository: https://github.com/MapsPeople/MapsIndoors-sdk-flutter
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter